---
- hosts: dev
  remote_user: root
  become: yes

  tasks:

  - name: Install packages
    apt:
      update_cache: no
      name:
        - ssh
        - zsh
      state: present

  - name: Ensure users exist on a host
    user:
      name: "{{ item.name }}"
      password: "{{ item.password }}"
      home: "/home/{{ item.name }}"
      shell: /usr/bin/zsh
      groups: "{{ item.groups }}"
      append: yes
    with_items:
      - { name: ansible, groups: [ansible, sudo, adm], password: '$6$salt&sugar$nwJ71kBrf9zuJDViI/iMYe/I3eVVTqkF8TAzJ1g6kkxVHKvtDtlJgizhSZtw3jjfyt2E0IXRqaaFjNjH9MdCE/' }

  - name: Create .ssh directories
    file:
      path: "/home/{{ item }}/.ssh"
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: 0700
    with_items:
      - ansible

  - name: Copy authorized public keys
    copy:
      src: authorized_keys
      dest: "/home/{{ item }}/.ssh"
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: 0644
    with_items:
      - ansible

  - name: Generate SSH keypair
    become: no
    openssh_keypair:
      path: "/home/{{ item }}/.ssh/id_25519_new"
      type: ed25519
      group: "{{ item }}"
      owner: "{{ item }}"
      mode: 0600
      force: yes
    with_items:
      - ansible 