---
- hosts: dev
  become: yes


  tasks:

  - name: Copy SSH files
    copy:
      src: ssh/
      dest: "{{ item.home }}/.ssh/"
      owner: "{{ item.name }}"
      group: "{{ item.name }}"
      mode: preserve
    with_items: "{{ users }}"

