---
- hosts: dev
  become: yes


  tasks:

  - name: Install packages
    apt:
      update_cache: no
      name:
        - ssh
        - zsh
      state: present

  - name: Ensure users exist on a host
    user:
      name: "{{ item.name }}"
      password: "{{ item.password }}"
      home: "{{ item.home }}"
      shell: "{{ item.shell }}"
      groups: "{{ item.groups }}"
      append: yes
    with_items: "{{ users }}"

  - name: Create .ssh directories
    file:
      path: "{{ item.home }}/.ssh"
      state: directory
      owner: "{{ item.name }}"
      group: "{{ item.name }}"
      mode: 0700
    with_items: "{{ users }}"

  - name: Copy authorized public keys
    copy:
      src: authorized_keys
      dest: "{{ item.home }}/.ssh"
      owner: "{{ item.name }}"
      group: "{{ item.name }}"
      mode: 0644
    with_items: "{{ users }}"

  - name: Generate SSH keypair
    openssh_keypair:
      path: "{{ item.home }}/.ssh/id_25519_new"
      type: ed25519
      group: "{{ item.name }}"
      owner: "{{ item.name }}"
      mode: 0600
    with_items: "{{ users }}"

  - name: Debug info
    debug:
      var: item.name
    with_items: "{{ users }}"
