---
- hosts: dev

  tasks:
    - name: Debug vault
      debug:
        msg:
          - "Variable secret_variable_1 = {{ vault_secret_variable_1 }}"
          - "Variable secret_variable_2 = {{ vault_secret_variable_2 }}"
          - "Variable non_secret_variable = {{ non_secret_variable }}"
          - "Variable variable_which_uses_secret_variable = {{ variable_which_uses_secret_variable }}"

    - name: Debug host variables
      debug:
        var: hostvars[inventory_hostname]["ansible_lsb"]
